name: ci

on:
  push:
    paths:
      - "**.f"
      - "**.f90"
      - "**.F90"
      - "**.c"
      - "**.cpp"
      - "**.h"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci.yml"
  workflow_dispatch:
  pull_request:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    env:
      FC: gfortran
      CMAKE_GENERATOR: "Ninja"

    steps:
    - uses: actions/checkout@v7

    - name: Configure CMake
      run: cmake -B build
